### ISSUE TITLE
Implementation Strategy for weather's Icons customs

### ISSUE THREAD

**Issue by mxtrar23** [JuanDavidRod/weather-aplication#6]
Implementation Strategy for weather's Icons customs use de code specific in fetch data from actual API.
i think mybe create some file that make a relation between  this code and new SVG icon or name from other library

**Comment by corners2wall** [comment]
Sounds easy, assign to me

**Comment by mxtrar23** [comment]
Hello @corners2wall sure,
basically what we want is not to use the API icons ([WeatherAPI](https://www.weatherapi.com/)), because we want simpler and monochromatic ones.
So we have to capture the variations they have in icons and use local icons like this one.

![image](https://github.com/JuanDavidRod/weather-aplication/assets/43935347/4da0ed60-2e4d-4ee3-9b5a-38efcdfe9423)

Tanks for help us
